
server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


  sleuth:
    reactor:
      instrumentation-type: decorate_on_each
  zipkin:
    base-url: http://localhost:9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
